### ISSUE TITLE
Social Icons (links)

### ISSUE THREAD

**Issue by apoodwivedi** [hacktoberfest2k20/CSS-reference#1]
Add social media icons in the website.
Using javascript

**Comment by UshasriMavuri1999** [comment]
Hey @apoorvadwivedi670 , Can you please assign this to me! 
I would like to work on this:)

**Comment by aansh-01** [comment]
Can i take up this issue😊

**Comment by Anuragjain20** [comment]
i can take  up this issue

**Comment by apoodwivedi** [comment]
@UshasriMavuri1999 Great , you are assigned.
