### ISSUE TITLE
Main section structure

### ISSUE THREAD

**Issue by apoodwivedi** [hacktoberfest2k20/CSS-reference#2]
A more attractive layout for the main structure .
Adding placeholders .

**Comment by aansh-01** [comment]
Can i take up this issue😊

**Comment by Anuragjain20** [comment]
can u provide a description  about what u exactly wanted and i  can take up this issue

**Comment by apoodwivedi** [comment]
@aansh-01 great , you are assigned.

**Comment by apoodwivedi** [comment]
@Anuragjain20 As aansh-01 asked first to work on this issue, so we'll be assigning them. But no worries, we'll be opening many user-friendly issues as well, hope to see you there : )
