### ISSUE TITLE
Home Page using HTML and CSS

### ISSUE THREAD

**Issue by ayushyadav0620** [hacktoberfest2k20/CSS-reference#8]
Structure of a Home Page inserting  a parallax using HTML and CSS.

**Comment by ayushyadav0620** [comment]
@Akshat05-tech  I would like to work on this issue can you please assign it to me?

**Comment by Akshat05-tech** [comment]
@ayushyadav0620 Ok You are assigned!!

**Comment by kartikagarwal9** [comment]
@Akshat05-tech Can i contribute
